apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: db.:5432  # Example: localhost:5432
    database: test
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: "disable"  # Change to "require" if SSL is needed
