services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "2000:8080"
    environment:
      RUN_ID: 'Test123'
      PREDICTIONS_STREAM_NAME: 'flower_predictions'
      AWS_DEFAULT_REGION: 'ap-southeast-2'
      MODEL_LOCATION: "/app/model/"

      KINESIS_ENDPOINT_URL: 'http://kinesis:4566/'
    volumes:
      - ./model:/app/model/
  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis